. ~/bin/dotfiles/zsh/env
. ~/bin/dotfiles/zsh/config
. ~/bin/dotfiles/zsh/aliases

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && .  ~/.localrc

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Hub
eval "$(hub alias -s)"

### Added by the Heroku Toolbelt
export PATH="./bin:/usr/local/heroku/bin:$PATH"
