. ~/bin/dotfiles/zsh/env
. ~/bin/dotfiles/zsh/config
. ~/bin/dotfiles/zsh/aliases

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && .  ~/.localrc

# rbenv
eval "$(rbenv init -)"

# Hub
eval "$(hub alias -s)"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
